"""Tests for remapping PrusaSlicer projects, using a small synthetic one."""

import zipfile

import pytest

from panda2prusa.convert import convert_file, default_extruder_map, describe, used_filaments
from panda2prusa.paint import used_states
from panda2prusa.prusa import (
    PrusaProject,
    _full_permutation,
    _remap_print_config,
    _split_strings,
    is_prusa_3mf,
)

MODEL = """<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">
 <metadata name="slic3rpe:Version3mf">1</metadata>
 <metadata name="Application">PrusaSlicer-2.9.6</metadata>
 <resources>
  <object id="1" type="model">
   <mesh>
    <vertices>
     <vertex x="0" y="0" z="0"/>
     <vertex x="10" y="0" z="0"/>
     <vertex x="0" y="10" z="0"/>
     <vertex x="0" y="0" z="10"/>
    </vertices>
    <triangles>
     <triangle v1="0" v2="2" v3="1" slic3rpe:mmu_segmentation="4"/>
     <triangle v1="0" v2="1" v3="3" slic3rpe:mmu_segmentation="8" slic3rpe:custom_supports="4"/>
     <triangle v1="1" v2="2" v3="3"/>
     <triangle v1="0" v2="3" v2b="2"/>
    </triangles>
   </mesh>
  </object>
 </resources>
 <build>
  <item objectid="1" transform="1 0 0 0 1 0 0 0 1 100 100 0" printable="1"/>
 </build>
</model>
"""

MODEL_CONFIG = """<?xml version="1.0" encoding="UTF-8"?>
<config>
 <object id="1" instances_count="1">
  <metadata type="object" key="name" value="Tetra"/>
  <metadata type="object" key="extruder" value="3"/>
  <volume firstid="0" lastid="1">
   <metadata type="volume" key="name" value="a"/>
   <metadata type="volume" key="volume_type" value="ModelPart"/>
   <metadata type="volume" key="extruder" value="0"/>
  </volume>
  <volume firstid="2" lastid="3">
   <metadata type="volume" key="name" value="b"/>
   <metadata type="volume" key="volume_type" value="ModelPart"/>
   <metadata type="volume" key="extruder" value="4"/>
  </volume>
 </object>
</config>
"""

PRINT_CONFIG = """; generated by PrusaSlicer 2.9.6
; extruder_colour = #111111;;#333333;#444444
; filament_colour = #AAAAAA;#BBBBBB;#CCCCCC;#DDDDDD
; filament_notes = ;;;
; filament_settings_id = "PLA one";"PETG; two";three;"four \\"x\\""
; filament_type = PLA;PETG;PLA;ASA
; filament_vendor = Generic
; inherits_cummulative = print;f1;f2;f3;f4;printer
; nozzle_diameter = 0.4,0.6,0.4,0.4
; perimeter_extruder = 1
; retract_length = 0.8,0.9,0.8,0.8
; support_material_extruder = 0
; temperature = 210,240,215,260
; wiping_volumes_matrix = 0,12,13,14,21,0,23,24,31,32,0,34,41,42,43,0
"""

CUSTOM_GCODE = """<?xml version="1.0" encoding="utf-8"?>
<custom_gcodes_per_print_z bed_idx="0">
<code print_z="2" type="2" extruder="1" color="" extra="" gcode="tool_change"/>
<mode value="MultiExtruder"/>
</custom_gcodes_per_print_z>"""

LAYER_RANGES = """<?xml version="1.0" encoding="utf-8"?>
<objects>
 <object id="1">
  <range min_z="0" max_z="1">
   <option opt_key="extruder">0</option>
   <option opt_key="layer_height">0.2</option>
  </range>
 </object>
</objects>"""

# Two roots, as PrusaSlicer writes for several beds: must pass through untouched.
WIPE_TOWER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    '<wipe_tower_information bed_idx="0" position_x="180"/>\n'
    '<wipe_tower_information bed_idx="1" position_x="180"/>'
)


@pytest.fixture
def sample(tmp_path):
    path = tmp_path / "sample.3mf"
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("3D/3dmodel.model", MODEL)
        z.writestr("Metadata/Slic3r_PE_model.config", MODEL_CONFIG)
        z.writestr("Metadata/Slic3r_PE.config", PRINT_CONFIG)
        z.writestr("Metadata/Prusa_Slicer_custom_gcode_per_print_z.xml", CUSTOM_GCODE)
        z.writestr("Metadata/Prusa_Slicer_layer_config_ranges.xml", LAYER_RANGES)
        z.writestr("Metadata/Prusa_Slicer_wipe_tower_information.xml", WIPE_TOWER)
        z.writestr("Metadata/thumbnail.png", b"\x89PNG not really")
    return str(path)


def _entries(path):
    with zipfile.ZipFile(path) as z:
        return {n: z.read(n) for n in z.namelist()}


def _config(entries):
    lines = entries["Metadata/Slic3r_PE.config"].decode().splitlines()
    return dict(line[2:].split(" = ", 1) for line in lines if " = " in line)


def test_describe(sample):
    assert is_prusa_3mf(sample)
    project = describe(sample)
    assert project.source == "prusa"
    assert project.producer == "PrusaSlicer-2.9.6"
    assert project.extruder_count == 4
    # paint states 1 and 2, object on 3, volume on 4, tool change to 1
    assert used_filaments(project) == [1, 2, 3, 4]
    assert default_extruder_map(project) == {1: 1, 2: 2, 3: 3, 4: 4}
    assert (project.objects, project.volumes, project.build_items, project.painted) == (1, 2, 1, 2)
    # an empty extruder colour falls back to the filament's
    assert project.filament_colors == ["#111111", "#BBBBBB", "#333333", "#444444"]
    assert project.filament_types == ["PLA", "PETG", "PLA", "ASA"]


def test_keep_is_a_verbatim_copy(sample, tmp_path):
    out = str(tmp_path / "out.3mf")
    result = convert_file(sample, out)
    assert result.source == "prusa"
    assert result.stats.extruder_map is None
    assert _entries(out) == _entries(sample)


def test_remap_moves_assignments_and_filaments(sample, tmp_path):
    out = str(tmp_path / "out.3mf")
    result = convert_file(sample, out, extruder_map={1: 2, 2: 1, 3: 4, 4: 3})
    assert result.stats.extruder_map == {1: 2, 2: 1, 3: 4, 4: 3}
    assert result.stats.painted_triangles == 2
    before, after = _entries(sample), _entries(out)
    assert list(after) == list(before)

    model = after["3D/3dmodel.model"].decode()
    codes = [line.split('mmu_segmentation="')[1].split('"')[0] for line in model.splitlines() if "mmu_seg" in line]
    assert [used_states(c) for c in codes] == [{2}, {1}]
    assert 'slic3rpe:custom_supports="4"' in model  # other painting is left alone
    strip = lambda text: [l.split("slic3rpe:mmu")[0] for l in text.splitlines()]
    assert strip(model) == strip(before["3D/3dmodel.model"].decode())

    cfg = after["Metadata/Slic3r_PE_model.config"].decode()
    assert '<metadata type="object" key="extruder" value="4"/>' in cfg
    assert '<metadata type="volume" key="extruder" value="0"/>' in cfg  # "inherit" stays
    assert '<metadata type="volume" key="extruder" value="3"/>' in cfg
    assert 'firstid="2" lastid="3"' in cfg

    conf = _config(after)
    assert conf["extruder_colour"] == ";#111111;#444444;#333333"
    assert conf["filament_colour"] == "#BBBBBB;#AAAAAA;#DDDDDD;#CCCCCC"
    assert conf["filament_settings_id"] == '"PETG; two";"PLA one";"four \\"x\\"";three'
    assert conf["filament_type"] == "PETG;PLA;ASA;PLA"
    assert conf["temperature"] == "240,210,260,215"
    assert conf["inherits_cummulative"] == "print;f2;f1;f4;f3;printer"
    assert conf["wiping_volumes_matrix"] == "0,21,24,23,12,0,14,13,42,41,0,43,32,31,34,0"
    assert conf["perimeter_extruder"] == "2"
    assert conf["support_material_extruder"] == "0"
    # tool-head hardware and scalars don't move
    assert conf["nozzle_diameter"] == "0.4,0.6,0.4,0.4"
    assert conf["retract_length"] == "0.8,0.9,0.8,0.8"
    assert conf["filament_vendor"] == "Generic"

    assert 'extruder="2"' in after["Metadata/Prusa_Slicer_custom_gcode_per_print_z.xml"].decode()
    for name in (
        "Metadata/Prusa_Slicer_layer_config_ranges.xml",
        "Metadata/Prusa_Slicer_wipe_tower_information.xml",
        "Metadata/thumbnail.png",
    ):
        assert after[name] == before[name]


def test_remap_round_trips(sample, tmp_path):
    there, back = str(tmp_path / "there.3mf"), str(tmp_path / "back.3mf")
    convert_file(sample, there, extruder_map={1: 3, 3: 4, 4: 1})
    convert_file(there, back, extruder_map={3: 1, 4: 3, 1: 4})
    assert _entries(back) == _entries(sample)


@pytest.mark.parametrize(
    "mapping, message",
    [
        ({1: 2}, "Filaments 1 and 2 are both mapped to extruder 2."),
        ({1: 5, 2: 1}, "has 4 tool(s)"),
        ({1: 0}, "1 or greater"),
    ],
)
def test_remap_rejects_bad_maps(sample, tmp_path, mapping, message):
    with pytest.raises(ValueError, match=message.replace("(", r"\(").replace(")", r"\)")):
        convert_file(sample, str(tmp_path / "out.3mf"), extruder_map=mapping)


def _project(used, count):
    return PrusaProject(source_path="", producer="", extruder_count=count, used=used)


def test_full_permutation_swaps_into_idle_tools():
    # moving onto an idle tool swaps the two filaments
    assert _full_permutation(_project([1], 4), {1: 3}) == {1: 3, 2: 2, 3: 1, 4: 4}
    # a chain 1 -> 2 -> 5 sends tool 5's idle filament back to the vacated tool 1
    assert _full_permutation(_project([1, 2], 5), {1: 2, 2: 5}) == {1: 2, 2: 5, 3: 3, 4: 4, 5: 1}
    # without a printer profile the slots run up to the highest tool mentioned
    assert _full_permutation(_project([1, 3], None), {3: 2}) == {1: 1, 2: 3, 3: 2}


def test_string_vectors_keep_quoted_separators():
    assert _split_strings('"a; b";c;;"d \\" ;"') == ['"a; b"', "c", "", '"d \\" ;"']
    text = '; start_filament_gcode = "M1 ; a";"M2 ; b"\n; nozzle_diameter = 0.4,0.4\n'
    assert _remap_print_config(text, {1: 2, 2: 1}).splitlines()[0] == (
        '; start_filament_gcode = "M2 ; b";"M1 ; a"'
    )


def test_rejects_prusaslicer_3_projects(tmp_path):
    path = tmp_path / "v3.3mf"
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("3D/3dmodel.model", MODEL.replace("2.9.6", "3.0.0-alpha12"))
        z.writestr("Metadata/PrusaSlicer3_project.json", "{}")
    with pytest.raises(ValueError, match="PrusaSlicer 3"):
        describe(str(path))


def test_own_output_is_remappable(tmp_path):
    """A converted file that PrusaSlicer hasn't saved yet has no printer profile."""
    path = tmp_path / "converted.3mf"
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("3D/3dmodel.model", MODEL.replace("PrusaSlicer-2.9.6", "panda2prusa"))
        z.writestr("Metadata/Slic3r_PE_model.config", MODEL_CONFIG)
    project = describe(str(path))
    assert project.extruder_count is None and project.filament_colors == []
    assert used_filaments(project) == [1, 2, 3, 4]
    out = str(tmp_path / "out.3mf")
    convert_file(str(path), out, extruder_map={4: 6})
    assert 'key="extruder" value="6"' in _entries(out)["Metadata/Slic3r_PE_model.config"].decode()
